name: Remove Duplicate URLs

on:
  push:
    branches:
      - master
    paths:
      - 1.txt

jobs:
  remove_duplicates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove duplicate URLs
        run: |
          # 在这个步骤中，你可以使用适当的命令或脚本来执行去重操作
          # 假设使用一个名为"remove_duplicates.js"的JavaScript脚本来去重URL
          node remove_duplicates.js 1.txt 2.txt
      - name: Set git default identity
        run: |
          git config --global user.email "501228112@qq.com"
          git config --global user.name "chendi0207"
      - name: Move file to master branch
        run: |
          git checkout master
          git add 2.txt
          git commit -m "Move file to master branch"
          git push origin master
